PROMPT POR FAVOR INGRESE SU UBICACION ACTUAL
ACCEPT xLatitud NUMBER PROMPT "LATITUD  : "
ACCEPT xLongitud NUMBER PROMPT "LONGITUD : "

PROMPT POR FAVOR INGRESE EL RANGO A BUSCAR
ACCEPT xRango PROMPT	"RANGO    :"


EXECUTE Bomberos.RPH(GPS(&xLatitud, &xLongitud, '', ''), &xRango);

@D:\P1\MENU_PRINCIPAL
