PROMPT BIENVENIDO AL REGISTRO DE MANTENIMIENTO DE HIDRANTES
PROMPT POR FAVOR INGRESE EL NUMERO DE LA SOLICITUD
ACCEPT xSol PROMPT      "NUMERO DE SOLICITUD : "

PROMPT POR FAVOR INGRESE EL NUMERO DE HIDRANTE
ACCEPT xNH PROMPT		"NUMERO DE HIDRANTE  : "

PROMPT POR FAVOR INGRESE EL CAUDAL DEL HIDRANTE
ACCEPT xCaud PROMPT		"CAUDAL  : "

PROMPT POR FAVOR INGRESE LOS DIAMETROS DE CADA BOQUILLA (0 SI NO APLICA)
ACCEPT xBoq1 NUMBER PROMPT		"BOQUILLA NUMERO 1: " DEFAULT 0
ACCEPT xBoq2 NUMBER PROMPT		"BOQUILLA NUMERO 2: " DEFAULT 0
ACCEPT xBoq3 NUMBER PROMPT		"BOQUILLA NUMERO 3: " DEFAULT 0
ACCEPT xBoq4 NUMBER PROMPT		"BOQUILLA NUMERO 4: " DEFAULT 0

PROMPT POR FAVOR INGRESE EL ESTADO DEL HIDRANTE (1 DEFECTUOSO, 0 FUNCIONAL)
ACCEPT xEstado PROMPT	"ESTADO  : "

EXECUTE Bomberos.registroTrabajoMantenimiento(&xSol, &xNH, &xCaud, &xBoq1, &xBoq2, &xBoq3, &xBoq4, &xEstado);
@D:\P1\MENU_PRINCIPAL