--MENU PRINCIPAL ----------------------
PROMPT BIENVENIDO AL SISTEMA
PROMPT POR FAVOR SELECCIONE UNA OPCION:
PROMPT 1.SOLICITAR LA INSTALACION O MANTENIMIENTO DEL HIDRANTE
PROMPT 2.REGISTRAR INSTALACION DEL HIDRANTE
PROMPT 3.REGISTRAR MANTENIMIENTO DE HIDRANTE
PROMPT 4.BUSCAR UN HIDRANTE CERCA DE SU UBICACION ACTUAL
PROMPT 0.SALIR
ACCEPT OP PROMPT "DIGITE EL NUMERO DE LA OPCION "

SET TERM OFF
	COLUMN SCRIPT new_value v_script
	SELECT CASE '&op'
		WHEN '1' THEN 'D:\P1\Solicita' 
		WHEN '2' THEN 'D:\P1\Instala' 
		WHEN '3' THEN 'D:\P1\Mantiene'
		WHEN '4' THEN 'D:\P1\Busca'
		WHEN '0' THEN 'D:\P1\Salir'
	ELSE 'D:\P1\MENU_PRINCIPAL'
	END AS SCRIPT
	FROM DUAL;
SET TERM ON
@&v_script
@D:\P1\MENU_PRINCIPAL