PROMPT BIENVENIDO AL REGISTRO DE SOLICITUD DE TRABAJO
PROMPT 1.SOLICITUD DE INSTALACION
PROMPT 2.SOLICITUD DE MANTENIMIENTO
PROMPT 0.REGRESAR AL MENU PRINCIPAL
ACCEPT OP PROMPT "DIGITE EL NUMERO DE LA OPCION "

SET TERM OFF
COLUMN SCRIPT new_value v_script
	SELECT CASE '&op'
		WHEN '1' THEN 'D:\P1\Sinst' 
		WHEN '2' THEN 'D:\P1\Smant'
		WHEN '0' THEN 'D:\P1\MENU_PRINCIPAL'
	ELSE 'D:\P1\Solicita'
	END AS SCRIPT
	FROM DUAL;
SET TERM ON
@&v_script
@D:\P1\MENU_PRINCIPAL